// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxnvdmepejjhvphqxopl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4bnZkbWVwZWpqaHZwaHF4b3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTU1MjYsImV4cCI6MjA3Mjc3MTUyNn0.t96U9mM_kg2UK2kzioSNmbT9dicWc2SVH-gyCwW-QZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});